export const PILLARS = [
  {
    id: 'authenticite',
    letter: 'A',
    name: 'Authenticite',
    fullName: 'Authenticite',
    description: 'Identite, mission, valeurs et capacites de la marque',
    color: '#f59e0b',
    bgGradient: 'from-amber-500/20 to-amber-600/5',
    icon: 'Fingerprint',
    variables: [
      'Mission de marque',
      'Valeurs fondamentales',
      'Heritage et histoire',
      'Capacites distinctives',
      'Culture interne',
    ],
  },
  {
    id: 'distinction',
    letter: 'D',
    name: 'Distinction',
    fullName: 'Distinction',
    description: 'Persona, positionnement, voix et reconnaissance',
    color: '#8b5cf6',
    bgGradient: 'from-violet-500/20 to-violet-600/5',
    icon: 'Star',
    variables: [
      'Persona de marque',
      'Positionnement unique',
      'Voix et ton',
      'Identite visuelle',
      'Elements de reconnaissance',
    ],
  },
  {
    id: 'valeur',
    letter: 'V',
    name: 'Valeur',
    fullName: 'Valeur',
    description: 'Promesse, produit, service, unit economics et budget',
    color: '#10b981',
    bgGradient: 'from-emerald-500/20 to-emerald-600/5',
    icon: 'Gem',
    variables: [
      'Proposition de valeur',
      'Offre produit/service',
      'Modele economique',
      'Structure de prix',
      'Budget marketing',
    ],
  },
  {
    id: 'engagement',
    letter: 'E',
    name: 'Engagement',
    fullName: 'Engagement',
    description: 'Touchpoints, metriques AARRR, rituels et campagnes',
    color: '#ec4899',
    bgGradient: 'from-pink-500/20 to-pink-600/5',
    icon: 'Heart',
    variables: [
      'Touchpoints client',
      'Funnel AARRR',
      'Rituels de marque',
      'Plan de campagne',
      'Communaute et engagement',
    ],
  },
  {
    id: 'risk',
    letter: 'R',
    name: 'Risk',
    fullName: 'Risk',
    description: 'Analyse SWOT sur chaque variable strategique',
    color: '#f97316',
    bgGradient: 'from-orange-500/20 to-orange-600/5',
    icon: 'Shield',
    variables: [
      'Forces (Strengths)',
      'Faiblesses (Weaknesses)',
      'Opportunites',
      'Menaces (Threats)',
      'Plan de mitigation',
    ],
  },
  {
    id: 'track',
    letter: 'T',
    name: 'Track',
    fullName: 'Track',
    description: 'Etat du marche, etudes et suivi de performance',
    color: '#06b6d4',
    bgGradient: 'from-cyan-500/20 to-cyan-600/5',
    icon: 'BarChart3',
    variables: [
      'Etude de marche',
      'Analyse concurrentielle',
      'KPIs de performance',
      'Tableau de bord',
      'Plan de suivi',
    ],
  },
] as const;

export type PillarId = (typeof PILLARS)[number]['id'];
